// Generated by CoffeeScript 1.3.3
(function() {
  var Guinea, Sidebar, Sounds, pig, side;

  Sidebar = (function() {

    function Sidebar() {
      this.el = $(".side");
      this.addItems();
      this.el.hammer().on('swiperight doubletap', '.foods li', function() {
        if (typeof pig !== "undefined" && pig !== null) {
          pig.say("Yummy! Thank you!");
        }
        return $(this).fadeOut('slow').delay(7000).fadeIn();
      });
      this.el.hammer().on('swiperight doubletap', '.play li', function() {
        if (typeof pig !== "undefined" && pig !== null) {
          pig.say("Yummy! Thank you!");
        }
        return $(this).fadeOut('slow').delay(7000).fadeIn();
      });
    }

    Sidebar.imageEl = function(path, im) {
      var name;
      name = im.split('.')[0];
      return "<li>\n	<img src='" + path + "/" + im + "' alt='" + name + "' />\n	<h5 class=\"subheader\">" + name + "</h5>\n</li>";
    };

    Sidebar.addItems = function() {
      var $section, im, _i, _j, _len, _len1, _ref, _ref1, _results;
      $section = this.el.find('.foods ul');
      _ref = ['carrots.png', 'greens.png', 'pear.png', 'pepper.png'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        im = _ref[_i];
        $section.append(Sidebar.imageEl('/images/foods', im));
      }
      $section = this.el.find('.play ul');
      _ref1 = ['wheel.jpg'];
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        im = _ref1[_j];
        _results.push($section.append(Sidebar.imageEl('/images', im)));
      }
      return _results;
    };

    return Sidebar;

  })();

  Sounds = (function() {

    function Sounds() {}

    Sounds.text = function(str) {
      return new Audio("http://tts-api.com/tts.mp3?q=" + (str.replace(' ', '+')));
    };

    Sounds.yumthankyou = new Audio("https://dl.dropboxusercontent.com/u/2724547/serve/autismhackathon/yummy.wav");

    return Sounds;

  })();

  Guinea = (function() {

    function Guinea() {
      var _this = this;
      this.tasks = [];
      $('.main').on('touchend', function() {
        if (_this.tasks.length === 0) {
          return Sounds.text("Do you want to play?").play();
        } else {
          return _this.tasks.shift()();
        }
      });
    }

    Guinea.prototype.setHungerInterval = function(msec) {
      var _this = this;
      return setInterval((function() {
        return _this.addSound("Could you feed me, please?");
      }), msec);
    };

    Guinea.prototype.addTask = function(fn) {
      return this.tasks.push(fn);
    };

    Guinea.prototype.addSound = function(snd) {
      var _this = this;
      if (!(snd.play != null)) {
        snd = Sounds.text(snd);
      }
      return this.addTask(function() {
        return snd.play();
      });
    };

    Guinea.prototype.say = function(snd) {
      if (!(snd.play != null)) {
        snd = Sounds.text(snd);
      }
      return snd.play();
    };

    return Guinea;

  })();

  side = new Sidebar;

  pig = new Guinea;

  pig.addSound("Hello! I am a guinea pig.");

  pig.addSound("Could you feed me, please?");

  pig.addSound("I need some exercise. Play time!");

}).call(this);
