// Generated by CoffeeScript 1.4.0
(function() {
  var Guinea, Sidebar, Sound, pig, side;

  Sound = (function() {

    function Sound() {}

    Sound.text = function(str) {
      return new Audio("http://tts-api.com/tts.mp3?q=" + (str.replace(' ', '+')));
    };

    Sound.feed = new Audio("/audio/feed.wav");

    Sound.fun = new Audio("/audio/fun.wav");

    Sound.gentle = new Audio("/audio/gentle.wav");

    Sound.hi = new Audio("/audio/hi.wav");

    Sound.play = new Audio("/audio/play.wav");

    Sound.tummyfeelsbetter = new Audio("/audio/tummyfeelsbetter.wav");

    Sound.tumrub = new Audio("/audio/tumrub.wav");

    Sound.yummy = new Audio("/audio/yummy.wav");

    return Sound;

  })();

  Sidebar = (function() {

    function Sidebar() {
      this.el = $(".side");
      this.addItems();
      this.el.hammer().on('swiperight doubletap', '.foods li', function() {
        pig.setImage("/images/eating.gif", 3000);
        pig.say(Sound.yummy);
        $(this).fadeOut('slow').delay(7000).fadeIn();
        return pig.addSound(Sound.tumrub);
      });
      this.el.hammer().on('swiperight doubletap', '.play li', function() {
        pig.setImage("/images/run.gif", 3000);
        return pig.say(Sound.fun);
      });
    }

    Sidebar.prototype.addItems = function() {
      var $section, im, _i, _j, _len, _len1, _ref, _ref1, _results;
      $section = this.el.find('.foods ul');
      _ref = ['carrots.png', 'greens.png', 'pear.png', 'pepper.png'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        im = _ref[_i];
        $section.append(Sidebar.imageEl('/images/foods', im));
      }
      $section = this.el.find('.play ul');
      _ref1 = ['wheel.jpg'];
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        im = _ref1[_j];
        _results.push($section.append(Sidebar.imageEl('/images', im)));
      }
      return _results;
    };

    Sidebar.imageEl = function(path, im) {
      var name;
      name = im.split('.')[0];
      return "<li>\n	<img src='" + path + "/" + im + "' alt='" + name + "' />\n	<h5 class=\"subheader\">" + name + "</h5>\n</li>";
    };

    return Sidebar;

  })();

  Guinea = (function() {

    function Guinea() {
      var _this = this;
      this.tasks = [];
      this.stage = $('.main').hammer();
      this.stage.on('touchend', function() {
        if (_this.tasks.length === 0) {
          return _this.say(Sound.play);
        } else {
          return _this.tasks.shift()();
        }
      });
      this.stage.on('pinchout', function() {
        return _this.say(Sound.tummyfeelsbetter);
      });
      this.stage.on('pinchin', function() {
        return _this.say(Sound.gentle);
      });
    }

    Guinea.prototype.setImage = function(url, revert) {
      var last, next,
        _this = this;
      last = $('.main').css("background-image");
      next = "url(" + url + ")";
      $('.main').css("background-image", next);
      return setTimeout((function() {
        return $('.main').css("background-image", last);
      }), +revert);
    };

    Guinea.prototype.setHungerInterval = function(msec) {
      var _this = this;
      return setInterval((function() {
        return _this.addSound(Sound.feed);
      }), msec);
    };

    Guinea.prototype.addTask = function(fn) {
      return this.tasks.push(fn);
    };

    Guinea.prototype.addSound = function(snd) {
      var _this = this;
      if (!(snd.play != null)) {
        snd = Sound.text(snd);
      }
      return this.addTask(function() {
        return snd.play();
      });
    };

    Guinea.prototype.say = function(snd) {
      if (!(snd.play != null)) {
        snd = Sound.text(snd);
      }
      return snd.play();
    };

    return Guinea;

  })();

  $(['/images/eating.gif', '/images/run.gif']).each(function() {
    return (new Image).src = this;
  });

  side = new Sidebar;

  pig = new Guinea;

  pig.setHungerInterval(30000);

  pig.addSound(Sound.hi);

  pig.addSound(Sound.play);

  pig.addSound(Sound.feed);

}).call(this);
