// Generated by CoffeeScript 1.4.0
(function() {
  var Guinea, Sidebar, Sounds, imageEl, pig, side;

  imageEl = function(path, im) {
    return "<li><img src='" + path + "/" + im + "' alt='" + (im.split('.')[0]) + "' /></li>";
  };

  pig = void 0;

  side = void 0;

  Sidebar = (function() {

    function Sidebar() {
      var $accordion, $section, im, _i, _j, _len, _len1, _ref, _ref1;
      this.$el = $(".side");
      $accordion = this.$el.find('.accordion');
      $section = $accordion.find('.foods ul');
      _ref = ['carrots.png', 'greens.png', 'pear.png', 'pepper.png'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        im = _ref[_i];
        $section.append(imageEl('/images/foods', im));
      }
      $accordion.find(".foods img").click(function() {
        if (pig != null) {
          pig.say("Yummy! Thank you!");
        }
        return $(this).fadeOut('slow').delay(7000).fadeIn();
      });
      $section = $accordion.find('.play ul');
      _ref1 = ['wheel.jpg'];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        im = _ref1[_j];
        $section.append(imageEl('/images', im));
      }
    }

    return Sidebar;

  })();

  Sounds = (function() {

    function Sounds() {}

    Sounds.text = function(str) {
      return new Audio("http://tts-api.com/tts.mp3?q=" + (str.replace(' ', '+')));
    };

    Sounds.yumthankyou = new Audio("https://dl.dropboxusercontent.com/u/2724547/serve/autismhackathon/yummy.wav");

    return Sounds;

  })();

  Guinea = (function() {

    function Guinea() {
      var _this = this;
      this.tasks = [];
      $('.main').click(function() {
        if (_this.tasks.length === 0) {
          return Sounds.text("Do you want to play?").play();
        } else {
          return _this.tasks.shift()();
        }
      });
    }

    Guinea.prototype.addTask = function(fn) {
      return this.tasks.push(fn);
    };

    Guinea.prototype.addSound = function(snd) {
      var _this = this;
      if (!(snd.play != null)) {
        snd = Sounds.text(snd);
      }
      return this.addTask(function() {
        return snd.play();
      });
    };

    Guinea.prototype.say = function(snd) {
      if (!(snd.play != null)) {
        snd = Sounds.text(snd);
      }
      return snd.play();
    };

    return Guinea;

  })();

  side = new Sidebar;

  pig = new Guinea;

  pig.addSound("Hello! I am a guinea pig.");

  pig.addSound("Could you feed me, please?");

  $('.main').backstretch('/images/guinea.jpg');

}).call(this);
