// Generated by CoffeeScript 1.3.3
(function() {
  var $foodSection, el, im, _i, _len, _ref;

  $('.main').backstretch('/images/guinea.jpg');

  $foodSection = $('.side .accordion .foods ul');

  _ref = ['carrots.png', 'greens.png', 'pear.png', 'pepper.png'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    im = _ref[_i];
    el = "<li><img src='images/foods/" + im + "' alt='" + (im.split('.')[0]) + "' /></li>";
    $foodSection.append(el);
  }

}).call(this);
